version: '3.9'
services:
  server:
    image: hyc0812/nestjs-typeorm-server:1.0  
    # build: 
    #   context: .
    #   dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: "mysql"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=digitaltwins
      - MYSQL_ROOT_PASSWORD=password
      # - MYSQL_TCP_PORT: 3305
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    # volumes:
    #   - ./init:/docker-entrypoint-initdb.d
    container_name: mysql8
    ports:
      - "3305:3306"
  


